### PR TITLE
[WIP] Upgrade to support datapackage v1

### PR DESCRIPTION
**Pull request by amercader**

### CODE REVIEW

**Comment by Stephen-Gates** [comment]
Thanks for working this. Very much appreciated

**Comment by Stephen-Gates** [comment]
@amercader any update on this work? Hope to take advantage of it next month if that's possible?

**Comment by amercader** [comment]
@Stephen-Gates I need to get these tests passing and then I'll merge and release a new version. I hope to have some time during this week to finish it off.

**Comment by amercader** [comment]
Tests in master fail because of https://github.com/ckan/ckan/issues/3869, but pass for 2.4 to 2.7

**Comment by amercader** [comment]
@Stephen-Gates this is now in master. I tagged this version 1.0.0. There might be some issues with v1 support but we can iron out these as we go

**Comment by Stephen-Gates** [comment]
Thanks @amercader
I will get this deployed to our testing environment and report any issues. 

Thanks again for you quick response 🙏🏼

**Comment by Stephen-Gates** [comment]
Hi @amercader, I met with a portal owner today and they are planning to install [ckanext-datapackager v1.0.0](https://github.com/frictionlessdata/ckanext-datapackager/releases/tag/v1.0.0) in a non-production environment for testing. They asked if there was any "policy" in place to make sure that this extension continues to work with future releases of CKAN. How do you suggest I reply?

**Comment by amercader** [comment]
@Stephen-Gates there is no written policy but we ensure that generic extensions like this one work across multiple CKAN versions. To ensure we run the automated tests against all versions as you can see on Travis: https://travis-ci.org/frictionlessdata/ckanext-datapackager/builds/287084200 is currently failing against CKAN master but that's fine as master is not production ready and it's a known issue). Hope this helps.

**Comment by Stephen-Gates** [comment]
this is now planned for testing on a government portal starting 20 Nov.

**Comment by amercader** [comment]
Fantastic, thanks @Stephen-Gates!

**Pull request merged**
